export {default as chess} from './chess'
export {default as checkers} from './checkers'
export {default as ludo} from './ludo'
export {default as snakes} from './snakes-and-ladders'
export {default as backgammon} from './backgammon'
export {default as connectfour} from './connect-four'
export {default as chess3p} from './chess-three-players'